dist: xenial
sudo: false

language: php

php:
  - 7.4
  - 8.0
  - 7.3
  - 7.2

matrix:
 allow_failures:
  - php: nightly
 fast_finish: true

install:
  - composer self-update
  - composer install

cache:
  directories:
    - $HOME/.composer/cache
